---
title: "Lab 6 comprehension"
author: "Soyeon Lee"
date: "10/17/2020"
output: html_document
---

```{r}
all_scores<-c(85,75,76,89,90,65,68,69)
permutation_matrix<-matrix(unlist(permn(all_scores)),ncol=8,byrow=TRUE)
group_A_means<-rowSums(permutation_matrix[,1:4])/4
group_B_means<-rowSums(permutation_matrix[,5:8])/4

```

```{r}
the_data<-read.csv("open_data/SchroederEpley2015data.csv",header=TRUE)

library(dplyr)

the_data%>%
  group_by(ï..CONDITION)%>%
  summarize(group_means=mean(Intellect_Rating))
```
```{r}
#problem: making a function
randomization_test<-function(A,B,num_permute)
all_scores <- c(A,B)
resample <- replicate(num_permute,sample(all_scores))
new_A_mean <- mean(resample[1:50])
new_B_mean <- mean(resample[51:100])
new_difference <- new_A_mean-new_B_mean
new_difference
#> [1] -1.963396

# Simulate the above process 10000 times
mean_differences <- c()
for(i in 1:10000){
  resample <- sample(all_scores)
  new_A_mean <- mean(resample[1:50])
  new_B_mean <- mean(resample[51:100])
  mean_differences[i] <- new_A_mean-new_B_mean
}
```


```{r}
group_one<-c(3,4,5,6,7)
group_two<-c(5,3,2,4,6)

randomization_test<-function(A,B,resamples=100){
  #calculate actual means
  group_A_mean<-mean(A)
  group_B_mean<-mean(B)
  mean_difference<-group_A_mean-group_B_mean
  
  #conduct randomization
  all_means<-c(A,B)
  
  possible_differences <- c()
  for(i in 1:resamples){
    resample <- sample(all_means)
    new_A_mean <- mean(resample[1:length(A)])
    new_B_mean <- mean(resample[(length(A)+1):length(all_means)])
    possible_differences[i] <- new_A_mean-new_B_mean
  }
  
  the_plot<-ggplot2::qplot(possible_differences)+
    ggplot2::geom_histogram(color="orange")+
    ggplot2::geom_vline(xintercept=mean_difference, color="red")+
    ggplot2::theme_classic()
 
  p_value<-length(possible_differences[possible_differences>=
                                       mean_difference])/resamples
   
  test_output<-list(A_mean=group_A_mean,
                    B_mean=group_B_mean,
                    difference=mean_difference,
                    randomization=possible_differences,
                    plot=the_plot,
                    p_value=p_value)
  
  return(test_output)
}

randomization_test(A=group_one,
                   B=group_two,
                   resamples=1000)

```

```{r}
the_data<-read.csv("open_data/SchroederEpley2015data.csv",header = TRUE)

library(dplyr)

group_0<-the_data%>%
  filter(ï..CONDITION==0)%>%
  select(Intellect_Rating)

group_0<-group_0$Intellect_Rating 
    
group_1<-the_data%>%
  filter(ï..CONDITION==1)%>%
  select(Intellect_Rating)

group_1<-group_1$Intellect_Rating

randomization_test(A=group_0,
                   B=group_1,
                   resamples=1000)
```

