---
title: "Lab 2 problem set review"
author: "Soyeon Lee"
date: "9/24/2020"
output: html_document
---


```{r}
gapminder_data<-read.table("open_data/gapminder.csv",sep=",", header=TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
```
```{r}
my_mean<-gapminder_data%>%group_by(year)%>%summarize(pop_mean=mean(pop))
```
```{r}
knitr::kable(my_mean)
```
```{r}
ggplot(gapminder_data,aes(x=year,y=lifeExp))+geom_bar(stat="identity")
```
```{r}
a<-1:10
mean(a)
median(a)
sd(a)
```
```{r}
mean(1:10)
mean(1:3)
gapminder_data%>%group_by(country)%>%summarize(gdp_mean=mean(gdpPercap))
```
```{r}
mean(c(1,2,3))
```
```{r}
the_sum<-sum(a)
the_numbers<-length(a)
the_mean<-the_sum/the_numbers
the_mean

```
```{r}
my_mean<-function(x){
the_mean<-sum(x)/length(x)  
return(the_mean)
}
```

```{r}
my_mean(a)
```
```{r}
scores<-c(1,2,3,4,5)

scores-3
```
```{r}
sum(scores-3)
```
```{r}
scores<-c(3,6,7,4,5,7,4,6,2,5)
mean(scores)
scores-mean(scores)
sum(scores-mean(scores))
round(sum(scores-mean(scores)))
```
```{r}
scores<-c(1,64,5,4,3,4,5,6,7,8,3)
```

for(i innumbers_to_test ){
```{r}
sum(scores-1)
sum(scores-2)
sum(scores-3)
sum(scores-4)
sum(scores-5)
sum(scores-6)
```
```{r}
sort(scores)
scores<-sort(scores)
scores

numbers_to_test<-min(scores):max(scores)

sum_dev<-c()

for(i in numbers_to_test){
  sum_dev[i]<-sum(scores-i)
}
sum_dev
```
```{r}
plot(sum_dev)
```
```{r}
plot(abs(sum_dev))
```
```{r}
which(sum_dev==0)
```
```{r}
sum_dev[10]
```
```{r}
which(sum_dev==0)
sum_dev[which(sum_dev==0)]
```
```{r}
scores<-1:20

sum_deviations<-c()
for(i in scores){
  sum_deviations[i]<-sum(scores-i)
}
sum_deviations
which(sum_deviations==0)
```
```{r}
numbers<-c(-10,-8,-1,2,5,6)
numbers
which(numbers==min(abs(numbers)))
which(abs(numbers)==min(abs(numbers)))
```
```{r}
scores<-1:20
sum_deviations<-c()

for(i in scores){
  sum_deviations[i]<-sum(scores-i)
}
sum_deviations
```
```{r}
which(abs(sum_deviations)==min(abs(sum_deviations)))
```

```{r}
test_for_mean<-function(scores,test_sequence){

sum_dev<-c()
  
for(i in 1:length(test_sequence)){
  sum_dev[i]<-sum(scores-test_sequence[i])
} 
mean_index<-which(abs(sum_dev)==min(abs(sum_dev)))
test_sequence[mean_index]
}

a<-c(1,4,3,2,4,3,5,4,6,5,7,6,8,7,9,8,7,6,7,6,5)
b<-seq(1,10,.1)

test_for_mean(a,b)
mean(a)
```
```{r}
gapminder_data<-read.table("open_data/gapminder.csv",sep=",",header=TRUE)
mean(gapminder_data$lifeExp)
mean(gapminder_data$pop)
mean(gapminder_data$gdpPercap)
```
```{r}
group_means<-gapminder_data%>%group_by(continent)%>%summarize(lifExp_mean=mean(lifeExp))
```
```{r}
group_means<-gapminder_data%>%
  group_by(continent)%>%
  summarize(lifeExp_mean=mean(lifeExp))

knitr::kable(group_means)
```
```{r}
library(dplyr)

group_means<-gapminder_data%>%
  group_by(continent, country)%>%
    summarize(mean_lifeExp=mean(lifeExp))

knitr::kable(head(group_means))
```
```{r}
table(group_means)
```
```{r}
group_means<-gapminder_data%>%
  group_by(continent)%>%
    summarize(mean=mean(lifeExp),
              median=median(lifeExp),
              sd=sd(lifeExp),
              var=var(lifeExp))
knitr::kable(group_means)
```
```{r}
group_means<-gapminder_data%>%
  group_by(continent)%>%
    summarize(mean_lifeExp=mean(lifeExp))

ggplot(group_means,aes(x=continent,y=mean_lifeExp))+
  geom_bar(stat="identity")+
    xlab("Continent")+
    ylab("Mean LifeExp")+
    ggtitle("lifeExp by Continent")
```
```{r}
ggplot(group_means,aes(x=continent,y=mean_lifeExp))+
  geom_bar(stat="identity")+
    xlab("Continent")+
    ylab("Life Expectancy")+
    theme_classic()+
     ggtitle("Life Expectancy by Continent")
```
```{r}
ggplot(group_means,aes(x=continent,y=mean_lifeExp,group=1))+
  geom_point()+
  geom_line()
```
```{r}
ggplot(group_means,aes(x=continent,y=mean_lifeExp,group=1))+
  geom_point()+
  geom_line()
```
```{r}
scores<-c(1,4,5,6,7,9)
numbers_to_test<-min(scores):max(scores)

sum_deviations<-c()
for(i in 1:length(numbers_to_test)){
  sum_deviations[i]<-sum(scores-numbers_to_test[i])
} 
which(sum_deviations==0)
mean(scores)
```
```{r}
sum_deviations
which(abs(sum_deviations)==min(abs(sum_deviations)))
```
```{r}
scores<-c(1,4,5,6,7,9)
numbers_to_test<-seq(from=min(scores),
                     to=max(scores),
                     by=.1111)

sum_deviations<-c()
for(i in 1:length(numbers_to_test)){
  sum_deviations[i]<-sum(scores-numbers_to_test[i])
} 
sum_deviations
```
```{r}
which(sum_deviations==0)
which(abs(sum_deviations)==min(abs(sum_deviations)))
```
```{r}
scores<-c(1,2,3,4,5)
mean(scores)
scores-mean(scores)
sum(scores-mean(scores))
```
```{r}
the_mean==which(scores-mean(scores)==0)
```

```{r}
my_median<-function(x){
  sorted_scores<-sort(x)
  for(i in sorted_scores){
    if(length(sorted_scores)/2==0){
      first_mid<-sorted_scores[length(sorted_scores)/2]
      second_mid<-sorted_scores[length(sorted_scores)/2+1]
      even_mid<-(first_mid+second_mid)/2
      return(even_mid)
    } else{
        a<-ceiling(length(sorted_scores)/2)
        odd_mid<-sorted_scores[a]
        return(odd_mid)
    }
  }
  
}
```

```{r}
b<-c(1,2,3,4,5,6)
my_median(b)
d<-c(1,2,3,4,5)
my_median(d)
```
```{r}
section<-c("morning","afternoon","evening")
avg_scores<-c(85,90,93)
scores_by_section<-data.frame(section,avg_scores)

ggplot(scores_by_section,aes(x=section,y=avg_scores))+
  geom_bar(stat="identity")
```
```{r}
instructor<-c(1,1,1,2,2,2)
section<-c("morning","afternoon","evening",
           "morning","afternoon","evening")
avg_scores<-c(75,78,80,88,76,63)

instr_sec_scores<-data.frame(instructor,section,avg_scores)

ggplot(instr_sec_scores,aes(x=section,y=avg_scores))+
  geom_bar(stat="identity")+
  facet_wrap(~instructor)
```
```{r}
world_happiness<-read.table("open_data/WHR2018.csv",sep=",",header=TRUE)

library(dplyr)
library(ggplot2)
social_supp<-world_happiness%>%
  group_by(year)%>%
    filter(year>=2010,
           year<=2015)%>%
      summarize(mean_ss=mean(Social.support),
                sd_ss=sd(Social.support))
   

knitr::kable(social_supp)
ggplot(social_supp,aes(x=year,y=mean_ss))+
    geom_bar(stat="identity")+
    geom_errorbar(aes(ymin=mean_ss-sd_ss,
                      ymax=mean_ss+sd_ss),
                      width=0.2)
```



