---
title: "Lab 3 problem set review"
author: "Soyeon Lee"
date: "9/27/2020"
output: html_document
---

```{r}
x<-c(1,2)
sample(x,size=2)
```
```{r}
sample(x,size=10,replace=TRUE)
```
```{r}
x<-c(2,1)
sample(x,size=10,replace=TRUE,prob=c(.9,.1))
```
```{r}
coin_outcomes<-c("heads","tails")
sample(coin_outcomes,size=10,replace=TRUE)
```
```{r}
distribution<-1:1000
sample(distribution,size=10,replace=FALSE)
```
```{r}
rnorm(10,mean=0,sd=1)
a<-rnorm(10,0,1)
```
```{r}
hist(rnorm(100,0,1))
```
```{r}
my_data<-data.frame(sample_data=rnorm(n=100,mean=0,sd=1),
                    sample=1)

library(ggplot2)

ggplot(my_data,aes(x=sample_data))+
  geom_histogram()

```
```{r}
my_data<-data.frame(sample_data=rnorm(100,0,1),
                    sample=rep(1:4,each=25))

ggplot(my_data,aes(x=sample_data))+
  geom_histogram()+
  facet_wrap(~sample)
```
```{r}
a<-runif(1000,min=1,max=1)

hist(runif(1000,min=0,max=1))
```
```{r}
my_sample<-runif(100,0,1)
my_sample
length(my_sample[my_sample<.05])
```
```{r}
hist(rexp(n=1000,rate=100))
```
```{r}
hist(rbinom(n=100,size=1,prob=.5))
x<-rbinom(n=100,size=5,prob=c(.5,.5))
print(x)
```
```{r}
hist(rweibull(n=1000,shape=3,scale=1))
```
```{r}
my_sample<-rnorm(1000,0,1)
library(moments)
mean(my_sample)
sd(my_sample)
skewness(my_sample)
kurtosis(my_sample)
hist(my_sample)
mean(rnorm(1000,0,1))
```
```{r}
hist(rexp(1000,rate=5))
hist(rexp(1000,rate=1000))
```
```{r}
my_sample<-rexp(1000,rate=100)
mean(my_sample)
sd(my_sample)
skewness(my_sample)
kurtosis(my_sample)
```

```{r}
flip<-c()
outcome<-c()
proportion_heads<-c()
proportion_tails<-c()

for(i in 1:5){
  flip[i]<-i
  outcome[i]<-sample(x=c(1,0),size=1)
  proportion_heads[i]<-sum(outcome)/length(outcome)
  proportion_tails[i]<-1-proportion_heads[i]
}
outcome
proportion_heads
```

```{r}
flip<-c()
outcome<-c()
proportion_heads<-c()
proportion_tails<-c()

for(i in 1:20){
  flip[i]<-i
  outcome[i]<-sample(x=c(1,0),size=1)
  proportion_heads[i]<-sum(outcome)/flip[i]
  proportion_tails[i]<-1-proportion_heads[i]
}

sim_data<-data.frame(flip,
                     outcome,
                     proportion_heads,
                     proportion_tails)

library(ggplot2)
ggplot(sim_data,aes(x=flip,y=proportion_heads))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept = 0.5,color="red")




```
```{r}
n<-seq(1000,100000,1000)
sample_mean<-c()
sample_sd<-c()

for(i in 1:length(n)){
  sim_sample<-rnorm(n[i],mean=100,sd=50)
  sample_mean[i]<-mean(sim_sample)
  sample_sd[i]<-sd(sim_sample)
}

sim_data<-data.frame(n,
                     sample_mean,
                     sample_sd)

ggplot(sim_data,aes(x=n,y=sample_mean))+
  geom_line()+
  geom_hline(yintercept = 100,color="red")
```
```{r}
ggplot(sim_data,aes(x=n,y=sample_sd))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept=50,color="red")
```
```{r}
#practice problem 1
sample<-c()
sample_mean<-c()

for(i in 1:5){
  sample[i]<-i
  sample_data<-sample(rnorm(25,mean=200,sd=100))
  sample_mean[i]<-mean(sample_data)
}

sim_data<-data.frame(sample,
                     sample_mean)

ggplot(sim_data,aes(x=sample,y=sample_mean))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept=100,color="red")
```
```{r}
observations<-rnorm(5*25,mean=200,sd=100)
sample<-rep(1:5,each=25)
sam_data<-data.frame(observations,sample)

library(dplyr)

group_summary<-sam_data%>%
  group_by(sample)%>%
    summarize(sample_mean=mean(observations),
              sample_sd=sd(observations))

knitr::kable(group_summary)

ggplot(group_summary,aes(x=sample,y=sample_mean))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=sample_mean-sample_sd,
                ymax=sample_mean+sample_sd),
                width=0.2)

```
```{r}

sample_size<-c(2,5,10,50,100)
sample_mean<-c()

for(i in 1:length(sample_size)){
  observations<-sample(rnorm(sample_size[i]*10000,10,5))
  sample_mean[i]<-mean(observations)
}

sim_data<-data.frame(sample_size,sample_mean)

knitr::kable(sim_data)
                    
ggplot(sim_data,aes(x=sample_size,y=sample_mean))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept=10,color="blue")

```
```{r}
sd_sample<-c()
sd_population<-c()
n<-c(2,5,10,50,100)

for (i in 1:length(sample_size)){
  sample<-sample(rnorm(n[i]*10000,mean=10,sd=5))
  sd_sample[i]<-sd(sample)
  sd_population[i]<-sqrt(var(sample)*(n[i]-1)/n[i])
}

sd_comparison<-data.frame(n,
                          estimate=c(sd_sample,sd_population),
                          formula=c(rep("N-1",5),rep("N",5)))

ggplot(sd_comparison,aes(x=n,
                         y=estimate,
                         group=formula,
                         color=formula))+
         geom_line()+
         geom_point()+
         coord_cartesian(ylim=c(3,6))
```

