---
title: "Lab problem set review"
author: "Soyeon Lee"
date: "9/14/2020"
output: html_document
---

```{r}
sum(seq(100,1000,100))
```
```{r}
a<-seq(100,1000,100)
the_sum<-0
for (i in a){
  the_sum<-the_sum+i
}
the_sum
```
```{r}
sum(c(1,3,2,4,3,5,4,3,4,5,6,5,6,7,6,5,6,5,4,3,4,5))
```
```{r}
seq_generator<-function()

```

```{r}

```

```{r}
seq(1,10,1)
sum(seq(1,10,1))
```
```{r}
seq_sum<-function(start,end,interval){
  the_seq<-seq(start,end,interval)
  the_sum<-sum(the_seq)
  return(list(the_seq,the_sum))
}
seq_sum(1,10,1)
```
```{r}
x<-c(1,2,3,4,5)
sum(x)/length(x)

```
```{r}
sum(1:100)

```
```{r}
1:5
1:10
-5:5
```
```{r}

```
```{r}
seq(from=1, to=2,length.out=10)
```
```{r}
sum(seq(1,2,length.out = 10))
sum(seq(from=1, to=2, length.out = 10))
```
```{r}
sum(seq(100,200,5))
X1<-100
Xn<-200
step<-5
(((Xn-X1)/step)+1)*((X1+Xn)/2)

```
```{r}
1:100

```
```{r}
100:1
```
```{r}
a<-1:5
a
rm(a)

```
```{r}
a<-c(1,6,3,2,8,9)
a[2]
a[4]
```
```{r}

my_sum<-function(X){
  sum<-0
  for(i in X)
    sum<-sum+i
  return(sum)
}  
my_sum(1:100)
```
```{r}
for (i in 1:5){
  print("hello")
}

```
```{r}
for(i in 1:5){
  print(i)
}
```
```{r}
my_sequence<-1:5
for(i in my_sequence){
  print(i)
}
```
```{r}
for(i in 1:10){
  if(i<=10){
    print(i)
  }else{
    break
  }
}
```
```{r}
i<-1
while(i<=5){
  print(i)
  i=i+1
}
```
```{r}
i<-1
repeat{
  print(i)
  i<-i+1
  if(i==6){
    break
  }
}
```
```{r}
a<-c(10,20,30,40,50)

the_sum<-0
for(i in a){
  the_sum<-the_sum+i
}
the_sum
sum(a)
```
```{r}
print_greeting<-function(){
  return(print("hello_world"))
}

print_greeting()
```
```{r}
function_a<-function(input){
  return(print(input))
}

function_a(1)

```
```{r}
add_one<-function(input){
  if(class(input)=="numeric"){
    temp<-input+1
    return(temp)
  }else{
    return(stop("input must be numeric"))
  }
}

add_one(1)
add_one(2)
add_one("d")
rm(temp)
```
```{r}
add_multiply<-function(input,second, third){
    temp<-(input+second)*third
    return(temp)
}
add_multiply(1,2,3)
```
```{r}
 
```

