---
title: "Lab6 comparisons"
author: "Soyeon Lee"
date: "3/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tibble)
library(tidyr)
library(dplyr)
options(dplyr.summarise.inform=FALSE)

smith_example<-tribble(
  ~same, ~different, ~imagery, ~photo, ~placebo,
  25,11,14,25,8,
  26,21,15,15,20,
  17,9,29,23,10,
  15,6,10,21,7,
  14,7,12,18,15,
  17,14,22,24,7,
  14,12,14,14,1,
  20,4,20,27,17,
  11,7,22,12,11,
  21,19,12,11,4
)%>%
  pivot_longer(cols=everything(),
               names_to="IV",
               values_to="DV")%>%
  mutate(IV=factor(IV, levels=c("same",
                                "different",
                                "imagery",
                                "photo",
                                "placebo")))

aov.out<-aov(DV~IV, data=smith_example)
summary(aov.out)

contrasts(smith_example$IV)

c1<-c(2,-3,2,2,-3)
c2<-c(2,0,-1,-1,0)S
c3<-c(0,0,+1,-1,0)
c4<-c(0,+1,0,0,-1)

my_contrasts<-cbind(c1,c2,c3,c4)

contrasts(smith_example$IV)<-my_contrasts

aov.out<-aov(DV~IV, data=smith_example)
full_summary<-summary.aov(aov.out,
                          split=list(IV=list("(1+3+4) vs (2+5)"=1,
                                             "(1) vs (3+4)"=2,
                                             "(3) vs (4)"=3,
                                             "(2) vs (5)"=4)))

full_summary
```
```{r}
library(papaja)
apa_table(apa_print(full_summary)$table)

full_summary[[1]]$'F value'[1]
mean(full_summary[[1]]$'F value'[2:5])
```

```{r}
group_means<-c(4,3,10,11)
(grand_mean<-mean(group_means))
(differences<-group_means-grand_mean)
(squared_differences<-differences^2)
(sum_squares<-sum(squared_differences))
```
```{r}
library(tibble)
fake_data<-tibble(IV=factor(c("A","B","C","D")),
                  DV=c(4,3,10,11))

contrasts(fake_data$IV)
```
```{r}
contrasts(fake_data$IV)[,'D']

contrasts(fake_data$IV)[,'D']*differences

grand_mean + (1*differences [4])
```
```{r}
(differences)

contrast_diff<-contrasts(fake_data$IV)* differences

contrast_gmean<-grand_mean *contrasts(fake_data$IV)

contrast_diff +contrast_gmean
```

```{r}
c1<-c(-1,-1,1,1)
c2<-c(1,-1,0,0)
c3<-c(0,0,-1,1)

my_contrasts<-cbind(c1,c2,c3)

contrasts(fake_data$IV)<-my_contrasts
contrasts(fake_data$IV)

cor(contrasts(fake_data$IV))
cor(my_contrasts)
```

```{r}
contrasts(fake_data$IV)

CaMa<-group_means * contrasts(fake_data$IV)
numerator<-1*(colSums(CaMa))^2
numerator/colSums(contrasts(fake_data$IV)^2)

```

```{r}
(fake_data$DV)

(grand_means<-c(7,7,7,7))

grand_means + contrasts(fake_data$IV)[,1]*3

grand_means +
  contrasts(fake_data$IV)[,1]*1 +
  contrasts(fake_data$IV)[,2]*1 +
  contrasts(fake_data$IV)[,3]*1
```
```{r}
fake_data2<-cbind(fake_data, contrasts(fake_data$IV))
fake_data2
lm(DV~c1+c2+c3,data=fake_data2)
summary(lm(DV~c1+c2+c3,data=fake_data2))
```

```{r}
grand_means+
  contrasts(fake_data$IV)[,1]*3.5+
  contrasts(fake_data$IV)[,2]*.5+
  contrasts(fake_data$IV)[,3]*.5
```

```{r}
fake_data<-tibble(IV=factor(c("A","B","C","D")),
                  DV=c(43,22,52,104))

contrasts(fake_data$IV)

c1<-c(-1,-1,1,1)
c2<-c(1,-1,0,0)
c3<-c(0,0,-1,1)
my_contrasts<-cbind(c1,c2,c3)

contrasts(fake_data$IV)<-my_contrasts

fake_data2<-cbind(fake_data,contrasts(fake_data$IV))

(lm(DV~c1+c2+c3,data=fake_data2))
summary(lm(DV~c1+c2+c3,data=fake_data2))

grand_means<-rep(mean(fake_data$DV),4)
grand_means

grand_means +
  contrasts(fake_data$IV)[,1]*22.75+
  contrasts(fake_data$IV)[,2]*10.5+
  contrasts(fake_data$IV)[,3]*26.00
```

```{r}
library(tibble)
sim_data<-tibble(DV=rnorm(6*100,0,1),
                 IV=factor(rep(1:6,each=100))
)

c1<-c(1,-1,0,0,0,0)
c2<-c(0,0,1,-1,0,0)
c3<-c(0,0,0,0,1,-1)
c4<-c(-1-1,2,2,-1,-1)
c5<-c(1,1,0,0,-1,-1)

orth_contrasts<-cbind(c1,c2,c3,c4,c5)

cor(orth_contrasts)

contrasts(sim_data$IV)<-orth_contrasts

(sim_data_output<-summary.aov(aov(DV~IV, sim_data), split=list(IV=list("c1"=1,
                                                "c2" = 2,
                                                "c3"= 3,
                                                "c4"= 4,
                                                "c5" = 5)
                                        )))
sim_data_output[[1]]$'Pr(>F)'[1:6]
```

```{r}
all_sim_data<-tibble()

for(i in 1:10000){
  sim_data<-tibble(DV=rnorm(6*100,0,1),
                   IV=factor(rep(1:6,each=100)))
  
  contrasts(sim_data$IV)<-orth_contrasts
  
  sim_output<-summary.aov(aov(DV~IV,sim_data),
                          split=list(IV=list("c1"=1,
                                             "c2"=2,
                                             "c3"=3,
                                             "c4"=4,
                                             "c5"=5)))
  
  sim_results<-tibble(type=c("omnibus",rep("contrast",5)),
                      p_values=sim_output[[1]]$`Pr(>F)`[1:6],
                      sim_num=rep(i,6))
  
  all_sim_data<-rbind(all_sim_data,sim_results)
}
```


```{r}
library(dplyr)

type_I_errors<-all_sim_data%>%
  mutate(type_I=p_values<.05)%>%
  group_by(type,sim_num)%>%
    summarize(counts=sum(type_I))%>%
  group_by(type,counts)%>%
    summarize(type_I_frequency=sum(counts))

knitr::kable(type_I_errors)
    
```

```{r}
type_I_errors%>%
  filter(type=="omnibus",
         counts==1)%>%
  pull(type_I_frequency)/10000
```
```{r}
type_I_errors%>%
  filter(type=="contrast",
         counts>0)%>%
  pull(type_I_frequency)%>%
  sum()/10000
```

```{r}

library(tibble)
romeo_juliet2<-tibble(subjects=1:20,
                     group=factor(rep(c("Context before",
                                 "Partial context",
                                 "Context after",
                                 "Without context"), each=5)),
                     comprehension=c(5,9,8,4,9,
                                     5,4,3,5,4,
                                     2,4,5,4,1,
                                     3,3,2,4,3
                                     ))

contrasts(romeo_juliet2$group)

c1<-c(1,1,1,-3)
c2<-c(0,0,1,-1)
c3<-c(3,-1,-1,-1)
c4<-c(1,-1,0,0)

new_contrasts<-cbind(c1,c2,c3,c4)
cor(new_contrasts)

contrasts(romeo_juliet2$group)<-c1
summary.aov(aov(comprehension~group,romeo_juliet2),
            split=list(group=list("c1"=1)))

contrasts(romeo_juliet2$group)<-c2
summary.aov(aov(comprehension~group,romeo_juliet2),
            split=list(group=list("c2"=1)))

contrasts(romeo_juliet2$group)<-c3
summary.aov(aov(comprehension~group,romeo_juliet2),
            split=list(group=list("c3"=1)))
```


```{r}
romeo_juliet2<-tibble(subjects=1:20,
                     group=rep(c("Context before",
                                 "Partial context",
                                 "Context after",
                                 "Without context"), each=5),
                     comprehension=c(5,9,8,4,9,
                                     5,4,3,5,4,
                                     2,4,5,4,1,
                                     3,3,2,4,3
                                     ))

romeo_juliet2$group<-factor(romeo_juliet2$group,
                            levels=c("Context before",
                                     "Partial context",
                                     "Context after",
                                     "Without context"))

contrasts(romeo_juliet2$group)

c1<-c(1,1,1,-3)
c2<-c(0,0,1,-1)
c3<-c(3,-1,-1,-1)
c4<-c(1,-1,0,0)

new_contrasts<-cbind(c1,c2,c3,c4)
cor(new_contrasts)

contrasts(romeo_juliet2$group)<-c1
summary.aov(aov(comprehension~group,romeo_juliet2),
            split=list(group=list("c1"=1)))

contrasts(romeo_juliet2$group)<-c2
summary.aov(aov(comprehension~group,romeo_juliet2),
            split=list(group=list("c2"=1)))

contrasts(romeo_juliet2$group)<-c3
summary.aov(aov(comprehension~group,romeo_juliet2),
            split=list(group=list("c3"=1)))
```




