---
title: "Learning lab 4"
author: "Soyeon Lee"
date: "9/28/2020"
output: html_document
---
```{r}
rolls<-sample(1:6,10000,replace=TRUE)

table(rolls)
table(rolls)/10000
```
```{r}
one<-sample(1:6,1000,replace=TRUE)
two<-sample(1:6,1000,replace=TRUE)
combined<-one+two

table(combined)
table(combined)/1000
```
```{r}
first<-rep(x=1:6,times=6)
second<-rep(x=1:6,each=6)
sum_rolls<-first+second

table(sum_rolls)

tru_probs<-table(sum_rolls)/length(sum_rolls)
sim_result<-table(combined)/1000

tru_probs-sim_result
```
```{r}
sample(c("A","B"),20,replace=TRUE,prob=c(.8,.2))
```
```{r}
sample(letters,50,replace=TRUE)
```
```{r}
my_letters<-sample(letters,50*5, replace=TRUE)

my_strings<-matrix(my_letters,ncol=5)

random_strings<-c()
for(i in 1:50){
  random_strings[i]<-paste0(my_strings[i,],collapse="")
}

random_strings

```
```{r}
#concept 2
coin_toss<-sample(c("H","T"),10,replace=TRUE)
table(coin_toss)/10
```
```{r}
sim_results<-replicate(10000,
          sample(c(1,0),10,replace=TRUE)
          )

number_of_heads<-colSums(sim_results)
table(number_of_heads)

```
```{r}
number_of_heads<-rbinom(10000,10,prob=.5)
table(number_of_heads)
table(number_of_heads)/10000
```
```{r}
flips<-sample(c("H","T"),30,replace=TRUE)
combos<-matrix(flips,ncol=2)

dim(combos)

flip_combos<-c()
for (i in 1:dim(combos)[1]){
  flip_combos[i]<-paste(combos[i,],collapse ="")
}  
flip_combos
  
```
```{r}
flips<-sample(c("H","T"),10,replace=TRUE)

sequence<-c()
for(i in 2:length(flips)){
  first_element<-flips[i-1]
  second_element<-flips[i]
  sequence[i]<-paste0(first_element,second_element)
}
table(sequence)
table(sequence)/9
```

```{r}
flips<-sample(c("H","T"),3,replace=TRUE)

sequence<-c()
for(i in 2:length(flips)){
  first_flip<-flips[i-1]
  second_flip<-flips[i]
  sequence[i-1]<-paste0(first_flip,second_flip)
}

table(sequence)
table(sequence)/2
```
```{r}
simulated_sequence<-c(rbinom(10,1,.5),
                      rbinom(10,1,.6))
simulated_sequence

my_experience<-c()
my_belief<-c()

for(i in 1:length(simulated_sequence)){
  my_experience[i]<-simulated_sequence[i]
  my_belief[i]<-sum(my_experience)/length(my_experience)
}

my_belief
```
```{r}
sim_sequence<-c(rbinom(100,1,prob=.5),
                rbinom(100,1,prob=.6))

my_experience<-c()
my_belief<-c()

for(i in 1:length(sim_sequence)){
  my_experience[i]<-sim_sequence[i]
  my_belief[i]<-sum(my_experience)/length(my_experience)
}

plot(my_belief)
```
```{r}
sim_sequence<-c(rbinom(100,1,.5),
                rbinom(100,1,.6))

sim_sequence

my_events<-c()
my_belief<-c()

for(i in 1:length(sim_sequence) ){
  my_events[i]<-sim_sequence[i]
  
  if(i<=20){
    my_belief[i]<-sum(my_events)/length(my_events)
  }else{
    my_belief[i]<-sum(my_events[i:(i-21)])/length(my_events[i:(i-21)])
  }
}
plot(my_belief)
```
```{r}
sim_sequence<-c(rbinom(100,1,.5),
                rbinom(100,1,.6))

my_events<-c()
my_belief<-c()

#my_belief is based on a maximum of 20 my_events
for (i in 1:length(sim_sequence)){
  my_events[i]<-sim_sequence[i]
  if(i<20){
    my_belief[i]<-sum(my_events)/length(my_events)
  }else{
    my_belief[i]<-sum(my_events[i:(i-19)])/length(my_events[i:(i-19)])
  }
}

plot(my_belief)
```
```{r}
sim_results<-replicate(10000,
                       sample(x=c(1,0),10,replace=TRUE)
                       )

num_heads<-colSums(sim_results)
table(num_heads)
table(num_heads)/10000
```
```{r}
num_heads<-rbinom(10000,10,prob=.5)
table(num_heads)/10000
```
```{r}
flips<-sample(x=c("H","T"),size=10000, replace=TRUE)

sequence<-c()
for(i in 2:length(flips)){
  first_flip<-flips[i-1]
  second_flip<-flips[i]
  sequence[i-1]<-paste0(first_flip,second_flip)
}
table(sequence)/sum(length(flips)-1)
```
```{r}
flips<-sample(x=c("H","T"),size=10000,replace=TRUE)

sequence<-c()
for(i in 3:length(flips)){
  first<-flips[i-2]
  second<-flips[i-1]
  third<-flips[i]
  sequence[i-2]<-paste0(first, second, third,collapse = "")
}
table(sequence)
table(sequence)/sum(length(flips)-2)
```
```{r}
flips<-sample(x=c("H","T"),size=10000,replace=TRUE)

organ_flips<-matrix(flips,nrow=length(flips)/5,ncol=2)

sequence<-c()
for(i in 1:dim(organ_flips)[1]){
  sequence[i]<-paste(organ_flips[i,],collapse="")
}
table(sequence)

```
```{r}
my_letters<-sample(letters,50*5,replace=TRUE)

my_strings<-matrix(my_letters, ncol=5)

rancom_strings<-c()
for(i in dim(my_strings)[1]){
  random_strings[i]<-paste0(my_strings[i,],collapse = "")
}
random_strings

```
```{r}
paste('x',1:3,collapse ="")
paste0('x',1:3,collapse="")
```
```{r}
paste("a","b",collapse="")
paste0("a","b",collapse="")
```
```{r}
flips<-sample(c("H","T"),10000,replace=TRUE)

sequence<-c()
for(i in 2:length(flips)){
  first_flip<-flips[i-1]
  second_flip<-flips[i]
  sequence[i-1]<-paste0(first_flip,second_flip,collapse="")
}
table(sequence)/sum(length(sequence)-1)

```


